version: "3"

services:
    viz:
        image: dockersamples/visualizer
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        stop_grace_period: 1m30s
        ports:
            - "9000:8080"
        deploy:
            placement:
                constraints:
                    - node.labels.visualizer == true
